### ISSUE TITLE
Post-dev bug changes

### ISSUE THREAD

**Issue by tiffany-tang** [actnforchildren/mental_health_app#84]
I remember we had a conversation about this in summer. Though I just want to have it in writing. 

After dev, if we have some changes/errors we would like to address, what is the arrangement for that?

Changes/errors can include:
- Bugs
- Content
- Adding/removing a feature, or something similarly big

I imagine we would likely be coming for bugs and minor content changes if everything goes smooth in the next few days.

**Comment by iteles** [comment]
@tiffany-tang We briefly discussed this as you say!

There are two paths here (not mutually exclusive):
+ **Small issues like tiny bugs or changes in wording:** I suggested originally (and this is something that needs to be rediscussed with @Cleop and the team given timelines and scope) to keep half a day of one developer's time back at the end of the sprint, so that we can keep that as a little block of time to chip away at with any small things that come up in the next two weeks or so
  + In practice this would mean that @SimonLab would finish at the end of Friday morning rather than at the end of the day
+ **Larger changes but smaller than 5 days of work:** We have standard Service Level Agreements (SLAs) which we keep with a few of our clients, I can send you our standard terms if you'd like the AfC team to take a look?
+ **Further sprints:** Just get in touch and we'll discuss availability!

@Cleop @RobStallion @SimonLab What are your thoughts on point 1 above? Would it be a possibility?

**Comment by tiffany-tang** [comment]
@iteles Phew that's still how I remembered it. Thanks!

**Comment by iteles** [comment]
@tiffany-tang You could either use it for any small things that didn't fit into the scope of the project originally, small enhancements or have it refunded to you 👍

**Comment by Cleop** [comment]
I think that point 1 seems feasible based on our existing progress for the original scope.

And from our discussions so far it sounds like #56 is high on the priority list for things to look at after the original scope.

**Comment by tiffany-tang** [comment]
@Cleop then does that mean if we have small bug/content changes we will potentially have to pay for that to be done?

**Comment by tiffany-tang** [comment]
Closing as addressed during stand-up
